version: '3.9'

services: 
  places-db:
    image: postgres:latest
    environment: 
      - POSTGRES_USER=place
      - POSTGRES_PASSWORD=place-db-pwd
    ports:
      - "5492:5432"
      
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U place"]
      interval: 5s
      timeout: 5s
      retries: 6
      
    networks: 
      - places-network

  places-service:
    build: 
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    environment: 
      - QUARKUS_DATASOURCE_URL=jdbc:postgresql://places-db:5432/place
      - QUARKUS_DATASOURCE_USERNAME=place
      - QUARKUS_DATASOURCE_PASSWORD=place-db-pwd
    ports:
      - "9090:8080"
    depends_on: 
      - places-db
    networks: 
      - places-network


networks:
  places-network:
    driver: bridge

    
    
    